### ISSUE TITLE
Add a symlink from `*-conda_cos6-*` to `*-conda-*`

### ISSUE THREAD

**Issue by isuruf** [conda-forge/linux-sysroot-feedstock#17]
Otherwise, the CDT packages won't work.

**Comment by isuruf** [comment]
Hmm, that might not work.

**Comment by isuruf** [comment]
cc @beckermr, CDT packages currently don't work.

**Comment by beckermr** [comment]
What do you mean?

**Comment by beckermr** [comment]
I built a wheel with then

**Comment by isuruf** [comment]
I'm going to close this in favour of https://github.com/conda-forge/ctng-compilers-feedstock/issues/28
