### ISSUE TITLE
Adding `glibc-langpack-en` to 2.28 sysroot

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/linux-sysroot-feedstock#48]
After some initial work on the AlmaLinux 8 based Docker image in PR ( https://github.com/conda-forge/docker-images/pull/235 ), it was determined that `glibc-langpack-en` needed to be installed to solve some locale issues. Filing this issue to track updating the sysroot with these files.

cc @beckermr

**Comment by beckermr** [comment]
Ohhhhhh nvm. We are shipping all langpacks in the sysroot, not the minimal one. closing!

**Comment by jakirkham** [comment]
That's great! Thanks for checking Matt 🙏
