### ISSUE TITLE
Remove tzdata from sysroot content?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/linux-sysroot-feedstock#62]
A large part of the [content](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fnoarch%2Fsysroot_linux-64-2.17-h4a8ded7_14.conda) of `sysroot_linux-<arch>` is effectively the same as what's in [`tzdata`](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fnoarch%2Ftzdata-2024a-h0c530f3_0.conda), only shifted under
```
$PREFIX/<arch>-conda-linux-gnu/sysroot/usr/share/zoneinfo
```
instead of under `$PREFIX/share/zoneinfo`.

Without having done a manual diff (because I'm assuming the sysroots get out of date, while the tzdb keeps getting updated), the one noticeable difference I see is that the sysroot also contains yet more copies (variants?) of the tzdb under
```
$PREFIX/<arch>-conda-linux-gnu/sysroot/usr/share/zoneinfo/posix/...
$PREFIX/<arch>-conda-linux-gnu/sysroot/usr/share/zoneinfo/right/...
```

Perhaps it's a hassle to change or more convenient to keep the tzdb in the sysroot, but it seems like an odd duplication to me.

**Comment by isuruf** [comment]
Fixed in #66
