### ISSUE TITLE
Something broke detection of ld64.so on ppc

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/linux-sysroot-feedstock#67]
For building https://github.com/conda-forge/matplotlib-feedstock/pull/390, we initially got
```
   INFO (matplotlib-base,lib/python3.9/site-packages/matplotlib/_image.cpython-39-powerpc64le-linux-gnu.so):
       Needed DSO powerpc64le-conda-linux-gnu/sysroot/lib64/ld64.so.2 found in CDT/compiler package conda-forge/noarch::sysroot_linux-ppc64le==2.17=h23d7e6c_14
```
which had the following build environment:
```
    sysroot_linux-64:                          2.12-he073ed8_17           conda-forge
    sysroot_linux-ppc64le:                     2.17-h23d7e6c_14           conda-forge
```

Now, after #65 & #66, we get:
```
  ERROR (matplotlib-base,lib/python3.9/site-packages/matplotlib/_image.cpython-39-powerpc64le-linux-gnu.so): $RPATH/ld64.so.2 not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
```
This has the following build environment
```
    sysroot_linux-64:                          2.17-h4a8ded7_16           conda-forge
    sysroot_linux-ppc64le:                     2.17-h23d7e6c_16           conda-forge
```

I fail to see how the switch in the build-arch sysroot would change anything, but it's reproducible. Interestingly, this is not seen on aarch64, only ppc.

**Comment by isuruf** [comment]
This is a conda-build issue. Please open a conda-build issue.

**Comment by h-vetinari** [comment]
> This is a conda-build issue. Please open a conda-build issue.

Even so, it'll break a bunch of our feedstock until a fix in conda-build materializes. We should IMO revert #65 until then.

**Comment by isuruf** [comment]
Please open an issue in conda-build first as requested. This only affects feedstocks with overlinking errors enabled which is only a few. If it's widespread, we can revert.

**Comment by h-vetinari** [comment]
Ah, I just saw that matplotlib hasn't been rerendered, which would explain things.

**Comment by h-vetinari** [comment]
> Please open an issue in conda-build first as requested.

To open an issue I need to understand the situation better than I do now. You seem to know what's happening, I'm still looking to figure it out (e.g. if it occurs also on a correctly rerendered feedstock, why only ppc, etc.)

**Comment by h-vetinari** [comment]
Done
